### ISSUE TITLE
Xcode 12.2: /usr/include/mach/task.h:236:1: error: too few arguments provided to function-like macro invocation );

### ISSUE THREAD

**Issue by yurikoles** [openzfsonosx/openzfs#13]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| macOS 
Distribution Version	| Big Sur / 11.0.1 (20B29)
Linux Kernel	| N/A
Architecture	| x86_64
ZFS Version	| current macOS branch
SPL Version	| current macOS branch

### Describe the problem you're observing
Can't compile on recent stable Xcode 12.2 @ Big Sur 11.0.1

### Include any warning/errors/backtraces from the system logs

```
In file included from zfs_util.c:61:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:39:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/LaunchServices.h:23:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/IconsCore.h:23:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/OSServices.framework/Headers/OSServices.h:29:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/OSServices.framework/Headers/CSIdentity.h:43:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/Security.h:87:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecCode.h:35:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/xpc/xpc.h:337:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/launch.h:19:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/mach/mach.h:67:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/mach/mach_interface.h:49:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/mach/task.h:236:1: error: too few arguments provided to function-like
      macro invocation
);
^
../../../../include/sys/zfs_context.h:232:9: note: macro 'thread_create' defined here
#define thread_create(stk, stksize, func, arg, len, pp, state, pri)     \
        ^
1 error generated.
```

**Comment by yurikoles** [comment]
It seems like thread_create is defined twice:
In `/usr/include/mach/task.h:236:`

```c
kern_return_t thread_create
(
	task_t parent_task,
	thread_act_t *child_act
);
```

And in `include/sys/zfs_context.h:232`:

```c
#define	thread_create(stk, stksize, func, arg, len, pp, state, pri)	\
	zk_thread_create(func, arg, stksize, state)
```
